export class LocalProvider {
  constructor(config) {}

  async generateCommitMessage(prompt) {
    // Stub for local LLM
    console.log("\n[LocalProvider] Stub: returning dummy message");
    return "feat: update code (generated by local LLM)";
  }
}
